# .streamlit/config.toml

[server]
# run headless (no local browser)
headless = true
# Cloud provides $PORT automatically
port = $PORT
# disable CORS headers (prevents warnings)
enableCORS = false

[browser]
# disable the “Gather usage stats” banner
gatherUsageStats = false
