# .streamlit/config.toml

[server]
# Run in headless mode when deployed
headless = true

# Disable CORS (useful if embedding in an iframe or behind a proxy)
enableCORS = false

# Don’t specify a port here; let your hosting env assign $PORT automatically
# (port = 8501)

[theme]
# Customize your app’s look (optional)
primaryColor             = "#1E90FF"
backgroundColor          = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor                = "#000000"
font                     = "sans serif"
